language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

sudo: required

addons:
    apt:
        packages:
            - ghostscript
            - p7zip-full

install:
    - sudo add-apt-repository ppa:fontforge/fontforge --yes
    - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpoppler-dev libpoppler-private-dev libspiro-dev libcairo-dev libpango1.0-dev libfreetype6-dev libltdl-dev libfontforge-dev python-imaging python-pip firefox xvfb
    - sudo apt-get install libreoffice
    - sudo apt-get install unoconv
    - git clone https://github.com/coolwanglu/pdf2htmlEX.git
    - pushd pdf2htmlEX
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_SVG=ON .
    - make
    - sudo make install
    - popd
    - pip install python-magic
    - pip install coveralls
    - pip install codecov
    - python setup.py -q install

script:
    - coverage run setup.py test

after_success:
    - coveralls
    - codecov
