language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - pip install --user python-magic
    - pip install --user coveralls
    - pip install --user codecov
    - python setup.py -q install

script:
    - coverage run setup.py test

after_success:
    - coveralls
    - codecov
