[tool.poetry]
name = "kittengroomer"
version = "2.2.0"
description = "Standalone CIRCLean/KittenGroomer code."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"
repository = "https://github.com/CIRCL/PyCIRCLean"

readme = "README.md"

classifiers=[
    'License :: OSI Approved :: BSD License',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: File Sharing',
    'Topic :: Security',
]

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.5.2"
exifread = "^2.1.2"
pillow = "^7.2.0"
olefile = "^0.46"
oletools = "^0.55.1"
python-magic = "^0.4.18"
officedissector = {git = "https://github.com/grierforensics/officedissector.git"}

[tool.poetry.dev-dependencies]
tox = "^3.18.1"
pytest-cov = "^2.10.0"
PyYAML = "^5.3.1"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
